name: CI
on:
  push:
    paths-ignore:
      - "**.md"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Lint
        uses: pre-commit/action@v2.0.0
